# Important info
dataset_name: 'casia'
model_name: 'siameseNet18'
backbone: 'resnet18'

output_path: './reports'
random_seed: 42

# StratifiedShuffleSplit
train_size: 0.667
test_size: 0.333
# train_size: 0.334
# test_size: 0.666

# Datasets
final_shape: [1, 280, 320]
dataset_dir: './'
train_dataset:
  augment: True
  grayscale: True
  shuffle: True
  train: True
test_dataset:
  augment: False
  grayscale: True
  shuffle: False
  train: False


# Dataloader
train_dataloader:
  batch_size: 64
  shuffle: True
test_dataloader:
  batch_size: 64
  shuffle: False

# LR Scheduler
lr_scheduler:
  step_size: 8
  gamma: 0.1
  last_epoch: -1

# Training Fit
fit:
  n_epochs: 20
  log_interval: 2
  save_best: True
  save_after: 50
  metrics: ['triplet-accuracy']
  accuracy_margin: 1

# Model
output_num: 1

# loss
similarity_margin: 1.0
accuracy_threshold: 0.3

# 0: ContrastiveLoss
# 1: Binary Cross Entropy
loss_margin: 1

# Training
learning_rate: 0.001
